

name: osmatrix


on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]


jobs:

  linux:
    runs-on: ubuntu-latest #Ubuntu 18.04.5 LTS
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "os fingerprinting"
      run: hostnamectl status

# https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-nodejs
  linux-node-js:
    runs-on: ubuntu-latest #Ubuntu 18.04.5 LTS
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: "os fingerprinting"
      run: hostnamectl status
    - run: npm install
    # - run: npm run build --if-present #npm ERR! enoent This is related to npm not being able to find a file.
    # - run: npm test
      env:
        CI: true

# https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-nodejs
  windows-node-js:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: "osfingerprinting"
      run: systeminfo | more          
    - run: npm install
    # - run: npm run build --if-present #npm ERR! enoent This is related to npm not being able to find a file.
    # - run: npm test
      env:
        CI: true

# https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-nodejs
  macos-node-js:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: "osfingerprinting"
      run: sw_vers          
    - run: npm install
    # - run: npm run build --if-present #npm ERR! enoent This is related to npm not being able to find a file.
    # - run: npm test
      env:
        CI: true


  ubuntu-2004:
      runs-on: ubuntu-20.04
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "os fingerprinting"
        run: hostnamectl status
      

  ubuntu-1804:
        # Environment variables
        # https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#default-environment-variables
        env:
          # FIRST_NAME: Mona
          OPERATION: "update"
          CHANGELOGFILE: "samplechangelog.h2.sql"
          USERNAME: "liquibase"
          PASSWORD: "password"
          URL: "jdbc:h2:file:./example/h2tutorial"
        runs-on: ubuntu-18.04
        container: liquibase/liquibase:4.1 ## Docker Hub image that `container-job` executes in
        # Service containers to run with `container-job`
        # https://docs.github.com/en/free-pro-team@latest/actions/guides/about-service-containers#about-service-containers
        # services: # Label used to access the service container          
        #   redis: #running liquibase           
        #     image: liquibase/liquibase:4.1 # Docker Hub image
        services: # Label used to access the service container          
          liquibase: #running liquibase           
            image: liquibase/liquibase:4.1 # Docker Hub image
        # runs: 
        #   using: 'docker'
        #   image: 'docker://debian:stretch-slim'
        steps:
        - name: Checkout
          uses: actions/checkout@v1
        # - name: "os fingerprinting"
        #   run: hostnamectl status 
        # - name: "docker run"
        #   run: | 
        #       docker run \ 
        #       --rm -v $(pwd):$(pwd)\ liquibase/liquibase:4.1 \
        #       --classpath=$(pwd)/changelogs \
        #       --url=$URL \
        #       --changeLogFile=$CHANGELOGFILE \
        #       --username=$USERNAME \
        #       --password=$PASSWORD $OPERATION
        # - name: "docker ps -a"
        #   run: docker ps -a           
        # - name: "test env"
        #   run: echo $URL

  # windows:
  #   runs-on: windows-latest
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v1
  #   - name: "check if server is virtual"
  #     run: Systeminfo | findstr /i model   
  #   - name: "check the PROCESSOR_ARCHITECTURE environment variable.64-bit systems will say AMD64 and 32-bit systems should say x86"
  #     run: wmic OS get OSArchitecture     
  #   - name: "osfingerprinting"
  #     run: systeminfo | more  
  #   - name: "display all processes, executable path"
  #     run: wmic process list full         
  #   - name: "list of running services"
  #     run: tasklist         
  #   - name: "list of all processes along with their corresponding PID, and services that are tied to them"
  #     run: tasklist /svc  
  #   - name: "look for unusual services"
  #     run: net start                       
  #   - name: "query unusual services"
  #     run: sc query  

  # macos:
  #   runs-on: macos-latest
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v1
  #   - name: "brew update"
  #     run: brew update      
  #   - name: "brew upgrade"
  #     run: brew upgrade
  #   - name: "check on brew version"
  #     run: brew --version   #Homebrew 2.5.12   
  #   - name: "brew cask list"
  #     run:   brew list --cask #Warning: Calling brew cask list is deprecated! Use brew list [--cask] instead.
  #   - name: "brew list"
  #     run: brew list #List all the installed formulas
  #   - name: "Get OS X System Version"
  #     run: sw_vers       
  #   - name: "Get Mac System Details with system_profiler"
  #     run: system_profiler | more  
  #   - name: "osfingerprinting"
  #     run: uname -a                           
    # - name: "brew doctor"
    #   run: |
    #     brew doctor #Check brew for potential problems         