

name: osmatrix


on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]


jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "os fingerprinting"
      run: hostnamectl status

  ubuntu-2004:
      runs-on: ubuntu-20.04
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "os fingerprinting"
        run: hostnamectl status
      

  ubuntu-1804:
        runs-on: ubuntu-18.04
        steps:
        - name: Checkout
          uses: actions/checkout@v1
        - name: "os fingerprinting"
          run: hostnamectl status        